function xml(text){const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw Error('El Excel contiene XML inválido.');return doc;}
function tags(node,name){return [...node.getElementsByTagNameNS('*',name)];}
async function readXlsx(buffer){
 const bytes=new Uint8Array(buffer),v=new DataView(buffer),dec=new TextDecoder();let end=-1;
 for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(v.getUint32(i,true)===0x06054b50&&i+22+v.getUint16(i+20,true)===bytes.length){end=i;break;}
 if(end<0)throw Error('No es un XLSX válido o está protegido con contraseña.');
 const entries=new Map();let at=v.getUint32(end+16,true);const count=v.getUint16(end+10,true);
 for(let i=0;i<count;i++){if(v.getUint32(at,true)!==0x02014b50)throw Error('Archivo ZIP dañado.');const len=v.getUint16(at+28,true),extra=v.getUint16(at+30,true),comment=v.getUint16(at+32,true);const name=dec.decode(bytes.slice(at+46,at+46+len));entries.set(name,{method:v.getUint16(at+10,true),size:v.getUint32(at+20,true),rawSize:v.getUint32(at+24,true),offset:v.getUint32(at+42,true),flags:v.getUint16(at+8,true)});at+=46+len+extra+comment;}
 let total=0;async function read(path){const e=entries.get(path);if(!e)throw Error('Falta '+path+' en el Excel.');if(e.flags&1)throw Error('El archivo está cifrado.');total+=e.rawSize;if(e.rawSize>40000000||total>100000000)throw Error('El contenido del Excel es demasiado grande.');const start=e.offset+30+v.getUint16(e.offset+26,true)+v.getUint16(e.offset+28,true);const data=bytes.slice(start,start+e.size);if(e.method===0)return dec.decode(data);if(e.method!==8)throw Error('Compresión de Excel no compatible.');let stream;try{stream=new DecompressionStream('deflate-raw');}catch{throw Error('Abre este archivo con Chrome o Edge actualizado para leer el Excel sin internet.');}const result=await new Response(new Blob([data]).stream().pipeThrough(stream)).arrayBuffer();if(result.byteLength!==e.rawSize)throw Error('El archivo está incompleto.');return dec.decode(result);}
 const workbook=xml(await read('xl/workbook.xml')),rels=xml(await read('xl/_rels/workbook.xml.rels'));const paths=new Map(tags(rels,'Relationship').map(r=>[r.getAttribute('Id'),r.getAttribute('Target')]));
 const shared=entries.has('xl/sharedStrings.xml')?tags(xml(await read('xl/sharedStrings.xml')),'si').map(si=>tags(si,'t').map(t=>t.textContent).join('')):[];
 const sheets=tags(workbook,'sheet').sort((a,b)=>Number(norm(b.getAttribute('name')).includes('CONTEOFISICO'))-Number(norm(a.getAttribute('name')).includes('CONTEOFISICO')));const result={SheetNames:[],Sheets:{}};
 for(const sheet of sheets){const name=sheet.getAttribute('name'),id=sheet.getAttribute('r:id')||sheet.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id'),target=paths.get(id);if(!target)continue;const parts=(target.startsWith('/')?target.slice(1):'xl/'+target).split('/'),clean=[];for(const part of parts){if(part==='..')clean.pop();else if(part!=='.')clean.push(part);}const rows=[];const doc=xml(await read(clean.join('/')));
 for(const row of tags(doc,'row')){const rowIndex=Number(row.getAttribute('r'))-1;if(rowIndex<0||rowIndex>100000)throw Error('Demasiadas filas en el Excel.');const values=[];for(const c of tags(row,'c')){const ref=c.getAttribute('r')||'',letters=ref.match(/^[A-Z]+/)?.[0];if(!letters)continue;let col=0;for(const l of letters)col=col*26+l.charCodeAt(0)-64;const type=c.getAttribute('t'),raw=tags(c,'v')[0]?.textContent;let value='';if(type==='s')value=shared[Number(raw)]??'';else if(type==='inlineStr')value=tags(c,'t').map(t=>t.textContent).join('');else if(type==='e')value=raw||'#ERROR';else if(raw!==undefined)value=type==='str'?raw:(Number.isFinite(Number(raw))?Number(raw):raw);values[col-1]=value;}rows[rowIndex]=values;}
 for(let i=0;i<rows.length;i++)if(!rows[i])rows[i]=[];result.SheetNames.push(name);result.Sheets[name]=rows;
 if(rows.slice(0,50).some(row=>{const h=row.map(norm);return h.includes('CODIGO')&&h.includes('UBICACION')&&h.includes('TOTALENUNI');}))return result;
 }return result;
}

'use strict';
const $=id=>document.getElementById(id);
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const fmt=v=>new Intl.NumberFormat('es-PE',{maximumFractionDigits:3}).format(v);
function locationOf(v){let s=String(v??'').trim().toUpperCase().replace(/\s+/g,' ');const m=s.replace(/\s/g,'').match(/^R(\d{1,2})([A-D])(\d{1,2})(?:\.(\d))?$/);return m?'R'+m[1].padStart(2,'0')+m[2]+m[3].padStart(2,'0')+(m[4]?'.'+m[4]:''):s;}
function typeOf(v){const t=norm(v);return ({IMP:'IMP',IMPORTADO:'IMP',IMPORTACION:'IMP',EXP:'EXP',EXPORTACION:'EXP',EXPORTADO:'EXP',NAC:'NAC',NACIONAL:'NAC'})[t]||'SIN TIPO';}
function parseWorkbook(wb){for(const name of wb.SheetNames){const rows=wb.Sheets[name];for(let h=0;h<Math.min(50,rows.length);h++){const heads=rows[h].map(norm),c=heads.indexOf('CODIGO'),l=heads.indexOf('UBICACION'),q=heads.indexOf('TOTALENUNI'),t=heads.indexOf('TIPO');if(c<0||l<0||q<0)continue;const out=[],bad=[];for(let i=h+1;i<rows.length;i++){const row=rows[i],code=String(row[c]??'').trim();if(!code||norm(code).startsWith('TOTAL'))continue;const raw=row[q],qty=typeof raw==='number'?raw:Number(String(raw??'').trim());if(raw===''||raw==null||!Number.isFinite(qty)){bad.push(i+1);continue;}out.push({row:i+1,code,location:locationOf(row[l])||'SIN UBICACIÓN',qty,type:typeOf(t>=0?row[t]:'')});}if(bad.length)throw Error('Revisa TOTAL EN UNI en filas '+bad.slice(0,20).join(', ')+'. Recalcula y guarda el Excel.');if(!out.length)throw Error('La plantilla no contiene materiales.');return {records:out,sheet:name};}}throw Error('Se requieren CODIGO, UBICACIÓN y TOTAL EN UNI.');}
const CW=112,CH=100,GAP=3,TOP=60,BOTTOM=TOP+32*(CH+GAP);const boxes=[],racks=[],lanes=[],byLocation=new Map(),colorMap=new Map();let worldWidth=0;
function addBox(location,x,y,w=CW,h=CH,rack=0,path=false){const box={location,x,y,w,h,rack,path};boxes.push(box);byLocation.set(location,box);}
function build(){let x=25;for(let r=5;r<=19;r++){const split=[11,12,19].includes(r),letters=r%2?'ABCD':'DCBA',cols=split?[...letters].flatMap(l=>r%2?[l+'.1',l+'.2']:[l+'.2',l+'.1']):[...letters],bays=r<=9?14:32,width=cols.length*(CW+GAP)-GAP;racks.push({r,x,width,y:BOTTOM-bays*(CH+GAP)});for(let bay=bays;bay>=1;bay--)cols.forEach((c,i)=>{const [letter,suffix]=c.split('.');if(r===10&&letter==='A'&&bay<=6){if(bay===6)addBox('JAULA',x+i*(CW+GAP),BOTTOM-6*(CH+GAP),CW,6*(CH+GAP)-GAP,r);return;}const loc='R'+String(r).padStart(2,'0')+letter+String(bay).padStart(2,'0')+(suffix?'.'+suffix:'');const path=r!==19&&['A','B'].includes(letter)&&[7,8,23,24].includes(bay);addBox(loc,x+i*(CW+GAP),BOTTOM-bay*(CH+GAP),CW,CH,r,path);});x+=width+30;if(r%2===0){lanes.push({x,w:72});x+=92;}}worldWidth=x+25;for(const [i,z]of ['TRASVASE','OFICINA','PASILLO 4'].entries())addBox(z,25+i*220,BOTTOM+140,200,130);}
build();for(let r=5;r<=19;r++){const option=document.createElement('option');option.value=r;option.textContent='Rack '+r;$('rack').append(option);}
let records=[],groups=new Map(),selected=null,scale=.2,panX=15,panY=15,pending=false,loadId=0;const canvas=$('canvas'),ctx=canvas.getContext('2d');let vw=0,vh=0;
let savedColors={};try{savedColors=JSON.parse(localStorage.getItem('almacen-colores-v1')||'{}');if(!savedColors||typeof savedColors!=='object')savedColors={};}catch{}
for(const [code,value] of Object.entries(savedColors))if(/^#[0-9a-f]{6}$/i.test(value))colorMap.set(code,value);
function color(code){if(!colorMap.has(code)){let hash=2166136261;for(const c of code)hash=Math.imul(hash^c.charCodeAt(0),16777619)>>>0;let hue=hash%360,sat=65+(hash>>>9)%15,light=80+(hash>>>17)%10,c=`hsl(${hue} ${sat}% ${light}%)`;const used=new Set(colorMap.values());while(used.has(c)){hue=(hue+137.50776405)%360;c=`hsl(${hue.toFixed(6)} ${sat}% ${light}%)`;}colorMap.set(code,c);}return colorMap.get(code);}
function schedule(){if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;draw();});}
function rect(x,y,w,h,fill,stroke){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.strokeRect(x,y,w,h);}}
function text(s,x,y,size=15,fill='#17324a',maxWidth){ctx.fillStyle=fill;ctx.font=`600 ${size}px Segoe UI,Arial`;ctx.textAlign='center';ctx.textBaseline='middle';if(maxWidth)ctx.fillText(s,x,y,maxWidth);else ctx.fillText(s,x,y);}
let hoverLocation=null,animationFrame=0;
function draw(){const dpr=devicePixelRatio||1;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,vw,vh);ctx.fillStyle='#e7edf3';ctx.fillRect(0,0,vw,vh);ctx.translate(panX,panY);ctx.scale(scale,scale);const rack=$('rack').value,query=$('search').value.trim().toUpperCase(),lq=locationOf(query);const visible=b=>(b.x+b.w)*scale+panX>=0&&b.x*scale+panX<=vw&&(b.y+b.h)*scale+panY>=0&&b.y*scale+panY<=vh;
if(!rack){for(const lane of lanes){rect(lane.x,TOP,lane.w,BOTTOM-TOP,'#d3eadd','#ddb72b');text('↑',lane.x+lane.w/2,BOTTOM-70,40,'#367756');}rect(25,BOTTOM+40,worldWidth-50,65,'#d3eadd','#ddb72b');text('↔ PASILLO FRONTAL ↔',worldWidth/2,BOTTOM+73,22,'#367756');const left=racks.find(r=>r.r===10).x-20;rect(25,TOP,left-25,(32-14)*(CH+GAP)-20,'#fff','#99adbd');text('ZONA DE BLOQUEO',left/2,TOP+450,35,'#c55443');text('ZONA DE SALDOS',left/2,TOP+1300,35,'#c55443');}
for(const r of racks){if(rack&&String(r.r)!==rack)continue;rect(r.x-5,r.y-40,r.width+10,32,'#173b59');text('RACK '+r.r,r.x+r.width/2,r.y-24,19,'white');}
for(const b of boxes){if(rack&&b.rack&&String(b.rack)!==rack)continue;if(!visible(b))continue;const items=[...(groups.get(b.location)?.values()??[])];const match=!query||b.location.includes(lq)||items.some(i=>i.code.includes(query));ctx.globalAlpha=match?1:.2;if(b.path){rect(b.x,b.y,b.w,b.h,'#d3eadd','#deb72b');if(scale>.16){text('PASO',b.x+b.w/2,b.y+b.h/2-8,16,'#367756');text(b.location,b.x+b.w/2,b.y+b.h/2+15,11,'#367756');}ctx.globalAlpha=1;continue;}
rect(b.x,b.y,b.w,b.h,items.length===1?color(items[0].code):'#fff','#8399aa');const labelHeight=25,bodyHeight=b.h-labelHeight;if(items.length){const segment=bodyHeight/items.length;items.forEach((i,n)=>{rect(b.x+1,b.y+n*segment+1,b.w-2,segment-1,color(i.code));if(scale>.12){const f=Math.max(7,Math.min(21,segment/3));text(i.code,b.x+b.w/2,b.y+n*segment+segment*.35,f,'#17324a',b.w-8);text('('+fmt(i.qty)+')',b.x+b.w/2,b.y+n*segment+segment*.7,f-1,'#17324a',b.w-8);}});}else if(scale>.35)text('Vacía',b.x+b.w/2,b.y+bodyHeight/2,13,'#9aabba');rect(b.x+1,b.y+b.h-labelHeight,b.w-2,labelHeight-1,'#ffffffbb');if(scale>.10)text(b.location,b.x+b.w/2,b.y+b.h-labelHeight/2,12,'#173b59',b.w-4);if(selected===b.location){ctx.strokeStyle='#007e91';ctx.lineWidth=3/scale;ctx.strokeRect(b.x,b.y,b.w,b.h);}ctx.globalAlpha=1;}
// Contorno de cada rack, dibujado encima del plano para distinguir parejas.
for(const r of racks){if(rack&&String(r.r)!==rack)continue;ctx.strokeStyle='#050505';ctx.lineWidth=Math.max(4,2/scale);ctx.strokeRect(r.x-5,r.y-40,r.width+10,BOTTOM-r.y+40);}
const hovered=byLocation.get(hoverLocation);if(hovered&&(!rack||!hovered.rack||String(hovered.rack)===rack)){ctx.save();ctx.strokeStyle='#007e91';ctx.lineWidth=2.5/scale;ctx.shadowColor='#007e9188';ctx.shadowBlur=8/scale;ctx.strokeRect(hovered.x,hovered.y,hovered.w,hovered.h);ctx.restore();}
$('zoomlabel').textContent=Math.round(scale*100)+'%';}
function fit(){const r=racks.find(r=>String(r.r)===$('rack').value);const x=r?r.x-10:0,y=r?r.y-50:0,w=r?r.width+20:worldWidth,h=r?BOTTOM-y+20:BOTTOM+300;scale=Math.min(vw/w,vh/h)*.94;panX=(vw-w*scale)/2-x*scale;panY=(vh-h*scale)/2-y*scale;schedule();}
function resize(){const r=canvas.getBoundingClientRect();vw=r.width;vh=r.height;const dpr=devicePixelRatio||1;canvas.width=Math.round(vw*dpr);canvas.height=Math.round(vh*dpr);schedule();}new ResizeObserver(resize).observe(canvas);
function animateView(target){
 cancelAnimationFrame(animationFrame);const start={scale,panX,panY},time=performance.now();const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 if(reduced){scale=target.scale;panX=target.panX;panY=target.panY;schedule();return;}
 function step(now){const t=Math.min(1,(now-time)/160),ease=1-Math.pow(1-t,3);scale=start.scale+(target.scale-start.scale)*ease;panX=start.panX+(target.panX-start.panX)*ease;panY=start.panY+(target.panY-start.panY)*ease;schedule();if(t<1)animationFrame=requestAnimationFrame(step);}
 animationFrame=requestAnimationFrame(step);
}
// Zoom inmediato: los eventos consecutivos no reinician una animación.
function zoomAt(f,x,y){
 cancelAnimationFrame(animationFrame);
 const previous=scale,next=Math.min(4,Math.max(.025,previous*f));
 panX=x-(x-panX)*next/previous;
 panY=y-(y-panY)*next/previous;
 scale=next;schedule();
}
canvas.addEventListener('wheel',e=>{
 e.preventDefault();e.stopPropagation();
 cancelAnimationFrame(animationFrame);
 const rect=canvas.getBoundingClientRect();
 // Shift + rueda permite desplazar. Rueda, dos dedos y pellizco hacen zoom.
 if(e.shiftKey){panX-=e.deltaX||e.deltaY;panY-=e.deltaX?e.deltaY:0;schedule();return;}
 const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?vh:1);
 if(delta===0){panX-=e.deltaX;schedule();return;}
 zoomAt(Math.exp(-Math.max(-150,Math.min(150,delta))*.003),e.clientX-rect.left,e.clientY-rect.top);
},{passive:false});
let drag=null;canvas.onpointerdown=e=>{cancelAnimationFrame(animationFrame);canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};canvas.classList.add('dragging');};canvas.onpointermove=e=>{if(!drag)return;panX+=e.clientX-drag.x;panY+=e.clientY-drag.y;drag.moved ||= Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4;drag.x=e.clientX;drag.y=e.clientY;schedule();};canvas.onpointerup=e=>{if(drag&&!drag.moved){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left-panX)/scale,y=(e.clientY-r.top-panY)/scale;const b=boxes.find(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h&&(!$('rack').value||!b.rack||String(b.rack)===$('rack').value));if(b){selected=b.location;detail(b);schedule();}}drag=null;canvas.classList.remove('dragging');};canvas.onpointercancel=()=>{drag=null;canvas.classList.remove('dragging');};canvas.ondblclick=fit;
function table(parent,heads,rows){const t=document.createElement('table'),h=t.insertRow();for(const value of heads){const th=document.createElement('th');th.textContent=value;h.append(th);}for(const values of rows){const r=t.insertRow();for(const value of values)r.insertCell().textContent=value;}parent.append(t);}
function detail(b){$('detail').replaceChildren();const h=document.createElement('h2');h.textContent=b.location+(b.path?' · Paso peatonal':'');$('detail').append(h);const items=[...(groups.get(b.location)?.values()??[])];if(items.length)table($('detail'),['Código','Cantidad','Tipo'],items.map(i=>[i.code,fmt(i.qty),[...i.types].join(', ')]));else{const p=document.createElement('p');p.textContent=b.path?'Espacio de circulación.':'Ubicación vacía.';$('detail').append(p);}}
function legend(){const el=$('legend');el.replaceChildren();const types=['IMP','NAC','EXP'];if(records.some(r=>r.type==='SIN TIPO'))types.push('SIN TIPO');for(const type of types){const totals=new Map();for(const r of records)if(r.type===type)totals.set(r.code,(totals.get(r.code)||0)+r.qty);const sec=document.createElement('section');sec.className='typegroup';const h=document.createElement('h3');h.className=type;h.textContent=type+' · '+totals.size+' códigos';const list=document.createElement('div');list.className='chips';if(!totals.size)list.textContent='Sin materiales';for(const [code,qty]of [...totals].sort((a,b)=>a[0].localeCompare(b[0],'es',{numeric:true}))){const b=document.createElement('button');b.className='chip';b.style.background=color(code);b.textContent=code+' · '+fmt(qty)+' uni';b.onclick=()=>{$('search').value=code;focusMaterial(code);};const pair=document.createElement('div');pair.className='colorpair';const picker=document.createElement('input');picker.type='color';picker.value=toHex(color(code));picker.title='Color de '+code;picker.setAttribute('aria-label','Color de '+code);picker.oninput=()=>{colorMap.set(code,picker.value);savedColors[code]=picker.value;b.style.background=picker.value;schedule();};picker.onchange=()=>{try{localStorage.setItem('almacen-colores-v1',JSON.stringify(savedColors));}catch{$('status').textContent='Color actualizado; el navegador no permite guardarlo.';}};pair.append(b,picker);list.append(pair);}sec.append(h,list);el.append(sec);}}
function warnings(){
 const alerts=[],seen=new Map();
 for(const r of records){const box=byLocation.get(r.location);if(r.location==='SIN UBICACIÓN')alerts.push({...r,reason:'Sin ubicación'});else if(!box)alerts.push({...r,reason:'Ubicación fuera del plano'});else if(box.path)alerts.push({...r,reason:'Material en paso peatonal'});if(r.qty<0)alerts.push({...r,reason:'Cantidad negativa'});const key=JSON.stringify([r.code,r.location,r.type,r.qty]);if(seen.has(key))alerts.push({...r,reason:'Posible fila duplicada de fila '+seen.get(key)});else seen.set(key,r.row);}
 $('warnings').hidden=!alerts.length;$('warnings').replaceChildren();if(!alerts.length)return;const h=document.createElement('h2');h.textContent='Alertas del inventario · '+alerts.length;$('warnings').append(h);const p=document.createElement('p');p.textContent='Las filas duplicadas se conservan en los totales; verifica si corresponden a lotes distintos.';$('warnings').append(p);table($('warnings'),['Fila','Código','Ubicación','Cantidad','Alerta'],alerts.map(r=>[r.row,r.code,r.location,fmt(r.qty),r.reason]));
}
$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;const id=++loadId;$('status').textContent='Leyendo '+f.name+'…';try{if(!/\.xlsx$/i.test(f.name)||f.size>30*1024*1024)throw Error('Se requiere XLSX de máximo 30 MB.');const parsed=parseWorkbook(await readXlsx(await f.arrayBuffer()));if(id!==loadId)return;records=parsed.records;groups=new Map();for(const r of records){if(!groups.has(r.location))groups.set(r.location,new Map());const codes=groups.get(r.location);if(!codes.has(r.code))codes.set(r.code,{code:r.code,qty:0,types:new Set()});codes.get(r.code).qty+=r.qty;codes.get(r.code).types.add(r.type);color(r.code);}selected=null;$('detail').textContent='Selecciona una ubicación.';legend();warnings();metrics();schedule();$('status').textContent=f.name+' · '+records.length+' filas · '+fmt(records.reduce((s,r)=>s+r.qty,0))+' unidades';}catch(err){if(id===loadId)$('status').textContent='Error: '+err.message;}finally{if(id===loadId)e.target.value='';}};
let searchTimer;$('search').oninput=()=>{schedule();clearTimeout(searchTimer);searchTimer=setTimeout(()=>focusMaterial($('search').value.trim()),250);};$('rack').onchange=fit;$('clear').onclick=()=>{$('search').value='';$('rack').value='';fit();};resize();fit();legend();metrics();

// INDICADORES: se excluyen los pasos peatonales de la capacidad.
function metrics(){
 const valid=boxes.filter(b=>!b.path),occupied=valid.filter(b=>groups.has(b.location)),empty=valid.length-occupied.length;
 const values=[['Ubicaciones ocupadas',occupied.length],['Ubicaciones vacías',empty],['Unidades totales',fmt(records.reduce((sum,r)=>sum+r.qty,0))],['Ocupación',valid.length?(occupied.length/valid.length*100).toFixed(1)+'%':'0%'],['Fuera de almacenamiento',records.filter(r=>!byLocation.has(r.location)||byLocation.get(r.location).path).length+' filas']];
 $('metrics').replaceChildren();for(const [label,value] of values){const div=document.createElement('div');div.className='metric';const strong=document.createElement('strong');strong.textContent=value;const span=document.createElement('span');span.textContent=label;div.append(strong,span);$('metrics').append(div);}
 let stats=$('rackstats');if(!stats){stats=document.createElement('div');stats.id='rackstats';stats.className='rackstats';$('metrics').after(stats);}stats.replaceChildren();for(const rack of racks){const all=valid.filter(b=>b.rack===rack.r),used=all.filter(b=>groups.has(b.location)).length;const button=document.createElement('button');button.className='rackstat';button.textContent='R'+rack.r+' · '+used+'/'+all.length+' · '+(used/all.length*100).toFixed(0)+'%';button.onclick=()=>{$('rack').value=String(rack.r);fit();};stats.append(button);}
}
function focusMaterial(query){
 const previous={scale,panX,panY};
 if(!query){schedule();return;}const q=query.toUpperCase(),lq=locationOf(query);const matches=boxes.filter(b=>b.location.includes(lq)||[...(groups.get(b.location)?.keys()??[])].some(code=>code.includes(q)));if(!matches.length){schedule();return;}
 $('rack').value='';const left=Math.min(...matches.map(b=>b.x)),top=Math.min(...matches.map(b=>b.y)),right=Math.max(...matches.map(b=>b.x+b.w)),bottom=Math.max(...matches.map(b=>b.y+b.h));scale=Math.min(1.4,vw/(right-left+160),vh/(bottom-top+160));panX=vw/2-(left+right)/2*scale;panY=vh/2-(top+bottom)/2*scale;if(matches.length===1){selected=matches[0].location;detail(matches[0]);}const target={scale,panX,panY};scale=previous.scale;panX=previous.panX;panY=previous.panY;animateView(target);
