function xml(text){const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw Error('El Excel contiene XML inválido.');return doc;}
function tags(node,name){return [...node.getElementsByTagNameNS('*',name)];}
async function readXlsx(buffer){
 const bytes=new Uint8Array(buffer),v=new DataView(buffer),dec=new TextDecoder();let end=-1;
 for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(v.getUint32(i,true)===0x06054b50&&i+22+v.getUint16(i+20,true)===bytes.length){end=i;break;}
 if(end<0)throw Error('No es un XLSX válido o está protegido con contraseña.');
 const entries=new Map();let at=v.getUint32(end+16,true);const count=v.getUint16(end+10,true);
 for(let i=0;i<count;i++){if(v.getUint32(at,true)!==0x02014b50)throw Error('Archivo ZIP dañado.');const len=v.getUint16(at+28,true),extra=v.getUint16(at+30,true),comment=v.getUint16(at+32,true);const name=dec.decode(bytes.slice(at+46,at+46+len));entries.set(name,{method:v.getUint16(at+10,true),size:v.getUint32(at+20,true),rawSize:v.getUint32(at+24,true),offset:v.getUint32(at+42,true),flags:v.getUint16(at+8,true)});at+=46+len+extra+comment;}
 let total=0;async function read(path){const e=entries.get(path);if(!e)throw Error('Falta '+path+' en el Excel.');if(e.flags&1)throw Error('El archivo está cifrado.');total+=e.rawSize;if(e.rawSize>40000000||total>100000000)throw Error('El contenido del Excel es demasiado grande.');const start=e.offset+30+v.getUint16(e.offset+26,true)+v.getUint16(e.offset+28,true);const data=bytes.slice(start,start+e.size);if(e.method===0)return dec.decode(data);if(e.method!==8)throw Error('Compresión de Excel no compatible.');let stream;try{stream=new DecompressionStream('deflate-raw');}catch{throw Error('Abre este archivo con Chrome o Edge actualizado para leer el Excel sin internet.');}const result=await new Response(new Blob([data]).stream().pipeThrough(stream)).arrayBuffer();if(result.byteLength!==e.rawSize)throw Error('El archivo está incompleto.');return dec.decode(result);}
 const workbook=xml(await read('xl/workbook.xml')),rels=xml(await read('xl/_rels/workbook.xml.rels'));const paths=new Map(tags(rels,'Relationship').map(r=>[r.getAttribute('Id'),r.getAttribute('Target')]));
 const shared=entries.has('xl/sharedStrings.xml')?tags(xml(await read('xl/sharedStrings.xml')),'si').map(si=>tags(si,'t').map(t=>t.textContent).join('')):[];
 const sheets=tags(workbook,'sheet').sort((a,b)=>Number(norm(b.getAttribute('name')).includes('CONTEOFISICO'))-Number(norm(a.getAttribute('name')).includes('CONTEOFISICO')));const result={SheetNames:[],Sheets:{}};
 for(const sheet of sheets){const name=sheet.getAttribute('name'),id=sheet.getAttribute('r:id')||sheet.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id'),target=paths.get(id);if(!target)continue;const parts=(target.startsWith('/')?target.slice(1):'xl/'+target).split('/'),clean=[];for(const part of parts){if(part==='..')clean.pop();else if(part!=='.')clean.push(part);}const rows=[];const doc=xml(await read(clean.join('/')));
 for(const row of tags(doc,'row')){const rowIndex=Number(row.getAttribute('r'))-1;if(rowIndex<0||rowIndex>100000)throw Error('Demasiadas filas en el Excel.');const values=[];for(const c of tags(row,'c')){const ref=c.getAttribute('r')||'',letters=ref.match(/^[A-Z]+/)?.[0];if(!letters)continue;let col=0;for(const l of letters)col=col*26+l.charCodeAt(0)-64;const type=c.getAttribute('t'),raw=tags(c,'v')[0]?.textContent;let value='';if(type==='s')value=shared[Number(raw)]??'';else if(type==='inlineStr')value=tags(c,'t').map(t=>t.textContent).join('');else if(type==='e')value=raw||'#ERROR';else if(raw!==undefined)value=type==='str'?raw:(Number.isFinite(Number(raw))?Number(raw):raw);values[col-1]=value;}rows[rowIndex]=values;}
 for(let i=0;i<rows.length;i++)if(!rows[i])rows[i]=[];result.SheetNames.push(name);result.Sheets[name]=rows;
 if(rows.slice(0,50).some(row=>{const h=row.map(norm);return h.includes('CODIGO')&&h.includes('UBICACION')&&h.includes('TOTALENUNI');}))return result;
 }return result;
}

'use strict';
const $=id=>document.getElementById(id);
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const fmt=v=>new Intl.NumberFormat('es-PE',{maximumFractionDigits:3}).format(v);
function locationOf(v){let s=String(v??'').trim().toUpperCase().replace(/\s+/g,' ');const m=s.replace(/\s/g,'').match(/^R(\d{1,2})([A-D])(\d{1,2})(?:\.(\d))?$/);return m?'R'+m[1].padStart(2,'0')+m[2]+m[3].padStart(2,'0')+(m[4]?'.'+m[4]:''):s;}
function typeOf(v){const t=norm(v);return ({IMP:'IMP',IMPORTADO:'IMP',IMPORTACION:'IMP',EXP:'EXP',EXPORTACION:'EXP',EXPORTADO:'EXP',NAC:'NAC',NACIONAL:'NAC'})[t]||'SIN TIPO';}
function parseWorkbook(wb){for(const name of wb.SheetNames){const rows=wb.Sheets[name];for(let h=0;h<Math.min(50,rows.length);h++){const heads=rows[h].map(norm),c=heads.indexOf('CODIGO'),l=heads.indexOf('UBICACION'),q=heads.indexOf('TOTALENUNI'),t=heads.indexOf('TIPO');if(c<0||l<0||q<0)continue;const out=[],bad=[];for(let i=h+1;i<rows.length;i++){const row=rows[i],code=String(row[c]??'').trim();if(!code||norm(code).startsWith('TOTAL'))continue;const raw=row[q],qty=typeof raw==='number'?raw:Number(String(raw??'').trim());if(raw===''||raw==null||!Number.isFinite(qty)){bad.push(i+1);continue;}out.push({row:i+1,code,location:locationOf(row[l])||'SIN UBICACIÓN',qty,type:typeOf(t>=0?row[t]:'')});}if(bad.length)throw Error('Revisa TOTAL EN UNI en filas '+bad.slice(0,20).join(', ')+'. Recalcula y guarda el Excel.');if(!out.length)throw Error('La plantilla no contiene materiales.');return {records:out,sheet:name};}}throw Error('Se requieren CODIGO, UBICACIÓN y TOTAL EN UNI.');}
const CW=112,CH=100,GAP=3,TOP=60,BOTTOM=TOP+32*(CH+GAP);const boxes=[],racks=[],lanes=[],byLocation=new Map(),colorMap=new Map();let worldWidth=0;
function addBox(location,x,y,w=CW,h=CH,rack=0,path=false){const box={location,x,y,w,h,rack,path};boxes.push(box);byLocation.set(location,box);}
function build(){let x=25;for(let r=5;r<=19;r++){const split=[11,12,19].includes(r),letters=r%2?'ABCD':'DCBA',cols=split?[...letters].flatMap(l=>r%2?[l+'.1',l+'.2']:[l+'.2',l+'.1']):[...letters],bays=r<=9?14:32,width=cols.length*(CW+GAP)-GAP;racks.push({r,x,width,y:BOTTOM-bays*(CH+GAP)});for(let bay=bays;bay>=1;bay--)cols.forEach((c,i)=>{const [letter,suffix]=c.split('.');if(r===10&&letter==='A'&&bay<=6){if(bay===6)addBox('JAULA',x+i*(CW+GAP),BOTTOM-6*(CH+GAP),CW,6*(CH+GAP)-GAP,r);return;}const loc='R'+String(r).padStart(2,'0')+letter+String(bay).padStart(2,'0')+(suffix?'.'+suffix:'');const path=r!==19&&['A','B'].includes(letter)&&[7,8,23,24].includes(bay);addBox(loc,x+i*(CW+GAP),BOTTOM-bay*(CH+GAP),CW,CH,r,path);});x+=width+30;if(r%2===0){lanes.push({x,w:72});x+=92;}}worldWidth=x+25;for(const [i,z]of ['TRASVASE','OFICINA','PASILLO 4'].entries())addBox(z,25+i*220,BOTTOM+140,200,130);}
build();for(let r=5;r<=19;r++){const option=document.createElement('option');option.value=r;option.textContent='Rack '+r;$('rack').append(option);}
let records=[],groups=new Map(),selected=null,scale=.2,panX=15,panY=15,pending=false,loadId=0;const canvas=$('canvas'),ctx=canvas.getContext('2d');let vw=0,vh=0;
let savedColors={};try{savedColors=JSON.parse(localStorage.getItem('almacen-colores-v1')||'{}');if(!savedColors||typeof savedColors!=='object')savedColors={};}catch{}
for(const [code,value] of Object.entries(savedColors))if(/^#[0-9a-f]{6}$/i.test(value))colorMap.set(code,value);
function color(code){if(!colorMap.has(code)){let hash=2166136261;for(const c of code)hash=Math.imul(hash^c.charCodeAt(0),16777619)>>>0;let hue=hash%360,sat=65+(hash>>>9)%15,light=80+(hash>>>17)%10,c=`hsl(${hue} ${sat}% ${light}%)`;const used=new Set(colorMap.values());while(used.has(c)){hue=(hue+137.50776405)%360;c=`hsl(${hue.toFixed(6)} ${sat}% ${light}%)`;}colorMap.set(code,c);}return colorMap.get(code);}
function schedule(){if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;draw();});}
function rect(x,y,w,h,fill,stroke){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.strokeRect(x,y,w,h);}}
function text(s,x,y,size=15,fill='#17324a',maxWidth){ctx.fillStyle=fill;ctx.font=`600 ${size}px Segoe UI,Arial`;ctx.textAlign='center';ctx.textBaseline='middle';if(maxWidth)ctx.fillText(s,x,y,maxWidth);else ctx.fillText(s,x,y);}
let hoverLocation=null,animationFrame=0;
function draw(){const dpr=devicePixelRatio||1;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,vw,vh);ctx.fillStyle='#e7edf3';ctx.fillRect(0,0,vw,vh);ctx.translate(panX,panY);ctx.scale(scale,scale);const rack=$('rack').value,query=$('search').value.trim().toUpperCase(),lq=locationOf(query);const visible=b=>(b.x+b.w)*scale+panX>=0&&b.x*scale+panX<=vw&&(b.y+b.h)*scale+panY>=0&&b.y*scale+panY<=vh;
if(!rack){for(const lane of lanes){rect(lane.x,TOP,lane.w,BOTTOM-TOP,'#d3eadd','#ddb72b');}rect(25,BOTTOM+40,worldWidth-50,65,'#d3eadd','#ddb72b');const left=racks.find(r=>r.r===10).x-20;const divide=TOP+9*(CH+GAP),zoneBottom=TOP+(32-14)*(CH+GAP)-45;rect(25,TOP,left-25,divide-TOP-12,'#fff','#111');rect(25,divide+12,left-25,zoneBottom-divide-12,'#fff','#111');text('PFN',left/2,TOP+450,110,'#c55443');text('ZONA DE SALDOS',left/2,TOP+1300,100,'#c55443');}
for(const r of racks){if(rack&&String(r.r)!==rack)continue;rect(r.x-5,r.y-40,r.width+10,32,'#173b59');text('RACK '+r.r,r.x+r.width/2,r.y-24,19,'white');}
for(const b of boxes){if(rack&&b.rack&&String(b.rack)!==rack)continue;if(!visible(b))continue;const items=[...(groups.get(b.location)?.values()??[])];const match=!query||b.location.includes(lq)||items.some(i=>i.code.includes(query));ctx.globalAlpha=match?1:.2;if(b.path){rect(b.x,b.y,b.w+GAP,b.h+GAP,'#d3eadd');ctx.globalAlpha=1;continue;}
rect(b.x,b.y,b.w,b.h,items.length===1?color(items[0].code):'#fff','#8399aa');const labelHeight=25,bodyHeight=b.h-labelHeight;if(items.length){const segment=bodyHeight/items.length;items.forEach((i,n)=>{rect(b.x+1,b.y+n*segment+1,b.w-2,segment-1,color(i.code));if(scale>.12){const f=Math.max(7,Math.min(21,segment/3));text(i.code,b.x+b.w/2,b.y+n*segment+segment*.35,f,'#17324a',b.w-8);text('('+fmt(i.qty)+')',b.x+b.w/2,b.y+n*segment+segment*.7,f-1,'#17324a',b.w-8);}});}else if(scale>.35)text('Vacía',b.x+b.w/2,b.y+bodyHeight/2,13,'#9aabba');rect(b.x+1,b.y+b.h-labelHeight,b.w-2,labelHeight-1,'#ffffffbb');if(scale>.10)text(b.location,b.x+b.w/2,b.y+b.h-labelHeight/2,12,'#173b59',b.w-4);if(selected===b.location){ctx.strokeStyle='#007e91';ctx.lineWidth=3/scale;ctx.strokeRect(b.x,b.y,b.w,b.h);}ctx.globalAlpha=1;}
// Cada ubicación tiene su propio contorno, por encima de los colores.
for(const b of boxes){if(b.path||!visible(b)||(rack&&b.rack&&String(b.rack)!==rack))continue;ctx.strokeStyle='#111111';ctx.lineWidth=Math.max(2,1/scale);ctx.strokeRect(b.x,b.y,b.w,b.h);}
// Contorno de cada rack, dibujado encima del plano para distinguir parejas.
for(const r of racks){if(rack&&String(r.r)!==rack)continue;ctx.strokeStyle='#050505';ctx.lineWidth=Math.max(4,2/scale);ctx.strokeRect(r.x-5,r.y-40,r.width+10,BOTTOM-r.y+40);}
// Abrir conexiones en los bordes y marcar la ruta sin etiquetas.
ctx.save();for(const r of racks){if(rack&&String(r.r)!==rack)continue;const paths=boxes.filter(b=>b.rack===r.r&&b.path),levels=[...new Set(paths.map(b=>b.y))].sort((a,b)=>a-b);for(let i=0;i<levels.length;i++){const top=levels[i];let bottom=top+CH;while(i+1<levels.length&&levels[i+1]<=bottom+GAP){i++;bottom=levels[i]+CH;}const section=paths.filter(b=>b.y>=top&&b.y<bottom),left=Math.min(...section.map(b=>b.x)),right=Math.max(...section.map(b=>b.x+b.w));const start=left===r.x?r.x-30:left,end=right>=r.x+r.width-1?right+30:right;rect(start,top,end-start,bottom-top,'#d3eadd');ctx.strokeStyle='#bf9518';ctx.lineWidth=Math.max(2,1/scale);ctx.setLineDash([14,10]);ctx.beginPath();ctx.moveTo(start,(top+bottom)/2);ctx.lineTo(end,(top+bottom)/2);ctx.stroke();ctx.setLineDash([]);}}
ctx.restore();
const hovered=byLocation.get(hoverLocation);if(hovered&&(!rack||!hovered.rack||String(hovered.rack)===rack)){ctx.save();ctx.strokeStyle='#007e91';ctx.lineWidth=2.5/scale;ctx.shadowColor='#007e9188';ctx.shadowBlur=8/scale;ctx.strokeRect(hovered.x,hovered.y,hovered.w,hovered.h);ctx.restore();}
$('zoomlabel').textContent=Math.round(scale*100)+'%';}
function fit(){const r=racks.find(r=>String(r.r)===$('rack').value);const x=r?r.x-10:0,y=r?r.y-50:0,w=r?r.width+20:worldWidth,h=r?BOTTOM-y+20:BOTTOM+300;scale=Math.min(vw/w,vh/h)*.94;panX=(vw-w*scale)/2-x*scale;panY=(vh-h*scale)/2-y*scale;schedule();}
function resize(){const r=canvas.getBoundingClientRect();vw=r.width;vh=r.height;const dpr=devicePixelRatio||1;canvas.width=Math.round(vw*dpr);canvas.height=Math.round(vh*dpr);schedule();}new ResizeObserver(resize).observe(canvas);
function animateView(target){
 cancelAnimationFrame(animationFrame);const start={scale,panX,panY},time=performance.now();const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 if(reduced){scale=target.scale;panX=target.panX;panY=target.panY;schedule();return;}
 function step(now){const t=Math.min(1,(now-time)/160),ease=1-Math.pow(1-t,3);scale=start.scale+(target.scale-start.scale)*ease;panX=start.panX+(target.panX-start.panX)*ease;panY=start.panY+(target.panY-start.panY)*ease;schedule();if(t<1)animationFrame=requestAnimationFrame(step);}
 animationFrame=requestAnimationFrame(step);
}
// Zoom inmediato: los eventos consecutivos no reinician una animación.
function zoomAt(f,x,y){
 cancelAnimationFrame(animationFrame);
 const previous=scale,next=Math.min(4,Math.max(.025,previous*f));
 panX=x-(x-panX)*next/previous;
 panY=y-(y-panY)*next/previous;
 scale=next;schedule();
}
canvas.addEventListener('wheel',e=>{
 e.preventDefault();e.stopPropagation();
 cancelAnimationFrame(animationFrame);
 const rect=canvas.getBoundingClientRect();
 // Shift + rueda permite desplazar. Rueda, dos dedos y pellizco hacen zoom.
 if(e.shiftKey){panX-=e.deltaX||e.deltaY;panY-=e.deltaX?e.deltaY:0;schedule();return;}
 const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?vh:1);
 if(delta===0){panX-=e.deltaX;schedule();return;}
 zoomAt(Math.exp(-Math.max(-150,Math.min(150,delta))*.003),e.clientX-rect.left,e.clientY-rect.top);
},{passive:false});
let drag=null;canvas.onpointerdown=e=>{cancelAnimationFrame(animationFrame);canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};canvas.classList.add('dragging');};canvas.onpointermove=e=>{if(!drag)return;panX+=e.clientX-drag.x;panY+=e.clientY-drag.y;drag.moved ||= Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4;drag.x=e.clientX;drag.y=e.clientY;schedule();};canvas.onpointerup=e=>{if(drag&&!drag.moved){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left-panX)/scale,y=(e.clientY-r.top-panY)/scale;const b=boxes.find(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h&&(!$('rack').value||!b.rack||String(b.rack)===$('rack').value));if(b){selected=b.location;detail(b);schedule();}}drag=null;canvas.classList.remove('dragging');};canvas.onpointercancel=()=>{drag=null;canvas.classList.remove('dragging');};canvas.ondblclick=fit;
function table(parent,heads,rows){const t=document.createElement('table'),h=t.insertRow();for(const value of heads){const th=document.createElement('th');th.textContent=value;h.append(th);}for(const values of rows){const r=t.insertRow();for(const value of values)r.insertCell().textContent=value;}parent.append(t);}
function detail(b){$('detail').replaceChildren();const h=document.createElement('h2');h.textContent=b.location+(b.path?' · Paso peatonal':'');$('detail').append(h);const items=[...(groups.get(b.location)?.values()??[])];if(items.length)table($('detail'),['Código','Cantidad','Tipo'],items.map(i=>[i.code,fmt(i.qty),[...i.types].join(', ')]));else{const p=document.createElement('p');p.textContent=b.path?'Espacio de circulación.':'Ubicación vacía.';$('detail').append(p);}}
function legend(){const el=$('legend');el.replaceChildren();const types=['IMP','NAC','EXP'];if(records.some(r=>r.type==='SIN TIPO'))types.push('SIN TIPO');for(const type of types){const totals=new Map();for(const r of records)if(r.type===type)totals.set(r.code,(totals.get(r.code)||0)+r.qty);const sec=document.createElement('section');sec.className='typegroup';const h=document.createElement('h3');h.className=type;h.textContent=type+' · '+totals.size+' códigos';const list=document.createElement('div');list.className='chips';if(!totals.size)list.textContent='Sin materiales';for(const [code,qty]of [...totals].sort((a,b)=>a[0].localeCompare(b[0],'es',{numeric:true}))){const b=document.createElement('button');b.className='chip';b.style.background=color(code);b.textContent=code+' · '+fmt(qty)+' uni';b.onclick=()=>{$('search').value=code;focusMaterial(code);};const pair=document.createElement('div');pair.className='colorpair';const picker=document.createElement('input');picker.type='color';picker.value=toHex(color(code));picker.title='Color de '+code;picker.setAttribute('aria-label','Color de '+code);picker.oninput=()=>{colorMap.set(code,picker.value);savedColors[code]=picker.value;b.style.background=picker.value;schedule();};picker.onchange=()=>{try{localStorage.setItem('almacen-colores-v1',JSON.stringify(savedColors));}catch{$('status').textContent='Color actualizado; el navegador no permite guardarlo.';}};pair.append(b,picker);list.append(pair);}sec.append(h,list);el.append(sec);}}
function warnings(){
 const alerts=[],seen=new Map();
 for(const r of records){const box=byLocation.get(r.location);if(r.location==='SIN UBICACIÓN')alerts.push({...r,reason:'Sin ubicación'});else if(!box)alerts.push({...r,reason:'Ubicación fuera del plano'});else if(box.path)alerts.push({...r,reason:'Material en paso peatonal'});if(r.qty<0)alerts.push({...r,reason:'Cantidad negativa'});const key=JSON.stringify([r.code,r.location,r.type,r.qty]);if(seen.has(key))alerts.push({...r,reason:'Posible fila duplicada de fila '+seen.get(key)});else seen.set(key,r.row);}
 $('warnings').hidden=!alerts.length;$('warnings').replaceChildren();if(!alerts.length)return;const h=document.createElement('h2');h.textContent='Alertas del inventario · '+alerts.length;$('warnings').append(h);const p=document.createElement('p');p.textContent='Las filas duplicadas se conservan en los totales; verifica si corresponden a lotes distintos.';$('warnings').append(p);table($('warnings'),['Fila','Código','Ubicación','Cantidad','Alerta'],alerts.map(r=>[r.row,r.code,r.location,fmt(r.qty),r.reason]));
}
$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;const id=++loadId;$('status').textContent='Leyendo '+f.name+'…';try{if(!/\.xlsx$/i.test(f.name)||f.size>30*1024*1024)throw Error('Se requiere XLSX de máximo 30 MB.');const parsed=parseWorkbook(await readXlsx(await f.arrayBuffer()));if(id!==loadId)return;records=parsed.records;groups=new Map();for(const r of records){if(!groups.has(r.location))groups.set(r.location,new Map());const codes=groups.get(r.location);if(!codes.has(r.code))codes.set(r.code,{code:r.code,qty:0,types:new Set()});codes.get(r.code).qty+=r.qty;codes.get(r.code).types.add(r.type);color(r.code);}selected=null;$('detail').textContent='Selecciona una ubicación.';legend();warnings();metrics();schedule();$('status').textContent=f.name+' · '+records.length+' filas · '+fmt(records.reduce((s,r)=>s+r.qty,0))+' unidades';}catch(err){if(id===loadId)$('status').textContent='Error: '+err.message;}finally{if(id===loadId)e.target.value='';}};
let searchTimer;$('search').oninput=()=>{schedule();clearTimeout(searchTimer);searchTimer=setTimeout(()=>focusMaterial($('search').value.trim()),250);};$('rack').onchange=fit;$('clear').onclick=()=>{$('search').value='';$('rack').value='';fit();};resize();fit();legend();metrics();

// INDICADORES: se excluyen los pasos peatonales de la capacidad.
function metrics(){
 const valid=boxes.filter(b=>!b.path),occupied=valid.filter(b=>groups.has(b.location)),empty=valid.length-occupied.length;
 const values=[['Ubicaciones ocupadas',occupied.length],['Ubicaciones vacías',empty],['Unidades totales',fmt(records.reduce((sum,r)=>sum+r.qty,0))],['Ocupación',valid.length?(occupied.length/valid.length*100).toFixed(1)+'%':'0%'],['Fuera de almacenamiento',records.filter(r=>!byLocation.has(r.location)||byLocation.get(r.location).path).length+' filas']];
 $('metrics').replaceChildren();for(const [label,value] of values){const div=document.createElement('div');div.className='metric';const strong=document.createElement('strong');strong.textContent=value;const span=document.createElement('span');span.textContent=label;div.append(strong,span);$('metrics').append(div);}
 let stats=$('rackstats');if(!stats){stats=document.createElement('div');stats.id='rackstats';stats.className='rackstats';$('metrics').after(stats);}stats.replaceChildren();for(const rack of racks){const all=valid.filter(b=>b.rack===rack.r),used=all.filter(b=>groups.has(b.location)).length;const button=document.createElement('button');button.className='rackstat';button.textContent='R'+rack.r+' · '+used+'/'+all.length+' · '+(used/all.length*100).toFixed(0)+'%';button.onclick=()=>{$('rack').value=String(rack.r);fit();};stats.append(button);}
}
function focusMaterial(query){
 const previous={scale,panX,panY};
 if(!query){schedule();return;}const q=query.toUpperCase(),lq=locationOf(query);const matches=boxes.filter(b=>b.location.includes(lq)||[...(groups.get(b.location)?.keys()??[])].some(code=>code.includes(q)));if(!matches.length){schedule();return;}
 $('rack').value='';const left=Math.min(...matches.map(b=>b.x)),top=Math.min(...matches.map(b=>b.y)),right=Math.max(...matches.map(b=>b.x+b.w)),bottom=Math.max(...matches.map(b=>b.y+b.h));scale=Math.min(1.4,vw/(right-left+160),vh/(bottom-top+160));panX=vw/2-(left+right)/2*scale;panY=vh/2-(top+bottom)/2*scale;if(matches.length===1){selected=matches[0].location;detail(matches[0]);}const target={scale,panX,panY};scale=previous.scale;panX=previous.panX;panY=previous.panY;animateView(target);
}
function toHex(value){if(/^#[0-9a-f]{6}$/i.test(value))return value;const rgb=value.match(/hsl\(([\d.]+) ([\d.]+)% ([\d.]+)%\)/);if(!rgb)return '#d7eef8';const h=Number(rgb[1])/360,s=Number(rgb[2])/100,l=Number(rgb[3])/100,a=s*Math.min(l,1-l);const f=n=>{const k=(n+h*12)%12;return Math.round((l-a*Math.max(-1,Math.min(k-3,9-k,1)))*255).toString(16).padStart(2,'0');};return '#'+f(0)+f(8)+f(4);}
function exportImage(){cancelAnimationFrame(animationFrame);hoverLocation=null;
 const mode=$('exportscope').value;if(mode==='rack'&&!$('rack').value)throw Error('Selecciona un rack antes de exportar.');
 const state={vw,vh,scale,panX,panY,rack:$('rack').value,query:$('search').value,selected};
 try{if(mode==='all')$('rack').value='';$('search').value='';selected=null;vw=1800;vh=mode==='all'?1300:1800;canvas.width=vw*(devicePixelRatio||1);canvas.height=vh*(devicePixelRatio||1);fit();draw();return canvas.toDataURL('image/png');}finally{vw=state.vw;vh=state.vh;scale=state.scale;panX=state.panX;panY=state.panY;selected=state.selected;$('rack').value=state.rack;$('search').value=state.query;resize();}
}
$('exportpng').onclick=()=>{try{const url=exportImage(),a=document.createElement('a');a.href=url;a.download='Layout_'+($('exportscope').value==='all'?'Completo':'Rack_'+$('rack').value)+'.png';a.click();}catch(e){$('status').textContent=e.message;}};
$('exportpdf').onclick=()=>{try{const url=exportImage(),win=window.open('','_blank');if(!win)throw Error('Permite abrir la ventana de impresión para guardar el PDF.');win.document.write('<!doctype html><html lang="es"><head><title>Layout de almacén</title><style>@page{size:A3 landscape;margin:10mm}body{margin:0;font:14px Arial}img{width:100%;max-height:90vh;object-fit:contain}p{margin:8px 0}@media print{button{display:none}}</style></head><body><button onclick="window.print()">Imprimir / guardar como PDF</button><p>Layout de almacén</p><img alt="Plano del almacén"></body></html>');win.document.close();const img=win.document.querySelector('img');img.onload=()=>{win.focus();win.print();};img.src=url;}catch(e){$('status').textContent=e.message;}};

// Efecto de selección al pasar el mouse, sin reconstruir el plano.
canvas.addEventListener('pointermove',e=>{if(drag)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left-panX)/scale,y=(e.clientY-r.top-panY)/scale,rack=$('rack').value;const hit=boxes.find(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h&&(!rack||!b.rack||String(b.rack)===rack));const next=hit?.location||null;if(next!==hoverLocation){hoverLocation=next;canvas.title=next||'Arrastra para mover · Rueda para zoom';schedule();}});
canvas.addEventListener('pointerleave',()=>{hoverLocation=null;schedule();});

// XLSX con plano como imagen y leyenda editable al costado, sin dependencias.
function zipStored(files){
 const encoder=new TextEncoder(),parts=[],central=[];let offset=0;
 const crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
 for(const [path,value]of Object.entries(files)){const name=encoder.encode(path),data=typeof value==='string'?encoder.encode(value):value;let crc=0xffffffff;for(const byte of data)crc=crcTable[(crc^byte)&255]^(crc>>>8);crc=(crc^0xffffffff)>>>0;
 const local=new Uint8Array(30+name.length),v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,0x21,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);local.set(name,30);parts.push(local,data);
 const head=new Uint8Array(46+name.length),h=new DataView(head.buffer);h.setUint32(0,0x02014b50,true);h.setUint16(4,20,true);h.setUint16(6,20,true);h.setUint16(8,0x800,true);h.setUint16(14,0x21,true);h.setUint32(16,crc,true);h.setUint32(20,data.length,true);h.setUint32(24,data.length,true);h.setUint16(28,name.length,true);h.setUint32(42,offset,true);head.set(name,46);central.push(head);offset+=local.length+data.length;
 }
 const size=central.reduce((n,p)=>n+p.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,central.length,true);v.setUint16(10,central.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
}
function buildLayoutWorkbook(png,width,height,legendRows){
 const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',rel='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
 const col=n=>{let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;};
 const data=new Map(),merges=[],widths=new Map(),styles=['<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>'],fills=['<fill><patternFill patternType="none"/></fill>','<fill><patternFill patternType="gray125"/></fill>'],cache=new Map();
 function style(hex,font=0,border=1){const key=hex+':'+font+':'+border;if(cache.has(key))return cache.get(key);const id=styles.length,fill=fills.length;fills.push(`<fill><patternFill patternType="solid"><fgColor rgb="FF${hex.replace('#','').toUpperCase()}"/><bgColor indexed="64"/></patternFill></fill>`);styles.push(`<xf numFmtId="0" fontId="${font}" fillId="${fill}" borderId="${border}" xfId="0" applyFill="1" applyFont="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>`);cache.set(key,id);return id;}
 const white=style('#ffffff'),label=style('#eef3f7',1),head=style('#173b59',2),path=style('#d3eadd',1,17),verticalPath=style('#d3eadd',1,18),selectorStyle=style('#fff1a8',1),zoneStyle=style('#ffffff',3);
 function cell(r,c,v,s=white){if(!data.has(r))data.set(r,new Map());data.get(r).set(c,{v,s});}
 function block(r,c,rr,cc,v,s){for(let y=r;y<=rr;y++)for(let x=c;x<=cc;x++)cell(y,x,'',s);cell(r,c,v,s);if(r!==rr||c!==cc)merges.push(`${col(c)}${r}:${col(cc)}${rr}`);}
 const scope=$('exportscope').value,rack=$('rack').value;if(scope==='rack'&&!rack)throw Error('Selecciona un rack.');
 const selectedRacks=racks.filter(r=>scope==='all'||String(r.r)===rack),selectedBoxes=boxes.filter(b=>scope==='all'||b.rack===Number(rack));
 const maxBay=scope==='rack'&&Number(rack)<=9?14:32,slots=Math.max(1,...selectedBoxes.filter(b=>!b.path).map(b=>groups.get(b.location)?.size||0)),step=slots+1;
 const baySlots=new Map(),bayRows=new Map();let cursor=3;for(let bay=maxBay;bay>=1;bay--){const capacity=Math.max(1,...selectedBoxes.filter(b=>!b.path&&Number(b.location.match(/^R\d{2}[A-D](\d{2})/)?.[1])===bay).map(b=>groups.get(b.location)?.size||0));baySlots.set(bay,capacity);bayRows.set(bay,cursor);cursor+=capacity+1;}const bayRow=bay=>bayRows.get(bay),lastStorage=cursor-1;let next=1;const columns=new Map(),walk=[];
 for(const r of selectedRacks){const letters=r.r%2?'ABCD':'DCBA',split=[11,12,19].includes(r.r),cols=split?[...letters].flatMap(l=>r.r%2?[l+'.1',l+'.2']:[l+'.2',l+'.1']):[...letters],start=next;for(const c of cols){columns.set(r.r+':'+c,next);widths.set(next,15);next++;}const headerRow=r.r<=9?bayRow(14)-1:1;block(headerRow,start,headerRow,next-1,'RACK '+r.r,head);widths.set(next,3);if(scope==='all'&&r.r%2===0){widths.set(next,7);walk.push({c:next,r:r.r});}next++;}
 const lastCol=next-2,legendCol=lastCol+3,selectRef=col(legendCol+1)+'2',highlightRanges=[];
 function materialBlock(location,r,c,capacity=1){const items=[...(groups.get(location)?.values()??[])];for(let n=0;n<items.length;n++){const item=items[n];cell(r+n,c,item.code+'\n('+fmt(item.qty)+')',style(toHex(color(item.code))));highlightRanges.push(`${col(c)}${r+n}`);}if(items.length<capacity)block(r+items.length,c,r+capacity-1,c,'',white);cell(r+capacity,c,location,label);}
 for(const b of selectedBoxes){if(!b.rack)continue;if(b.location==='JAULA'){const c=columns.get('10:A');if(c){const first=bayRow(6),capacity=Math.max(baySlots.get(6),groups.get('JAULA')?.size||0);materialBlock('JAULA',first,c,capacity);for(let r=first+capacity+1;r<=lastStorage;r++)cell(r,c,'',white);cell(lastStorage,c,'JAULA',label);}continue;}
 const m=b.location.match(/^R(\d{2})([A-D])(\d{2})(?:\.(\d))?$/);if(!m)continue;const c=columns.get(Number(m[1])+':'+m[2]+(m[4]?'.'+m[4]:'')),r=bayRow(Number(m[3]));const capacity=baySlots.get(Number(m[3]));if(b.path)block(r,c,r+capacity,c,'',path);else materialBlock(b.location,r,c,capacity);}
 const shortStart=bayRow(14);
 for(const w of walk)block(w.r<=8?shortStart:3,w.c,lastStorage,w.c,'',verticalPath);
 if(scope==='all'){const zoneLast=columns.get('9:D');block(3,1,bayRow(23)-1,zoneLast,'PFN',zoneStyle);block(bayRow(23),1,shortStart-2,zoneLast,'ZONA DE SALDOS',zoneStyle);}
 block(lastStorage+2,1,lastStorage+2,lastCol,'',path);let lastRow=lastStorage+3;
 if(scope==='all'){let c=1;for(const zone of ['TRASVASE','OFICINA','PASILLO 4']){const capacity=Math.max(1,groups.get(zone)?.size||0);materialBlock(zone,lastStorage+4,c,capacity);lastRow=Math.max(lastRow,lastStorage+4+capacity);c+=2;}}
 widths.set(legendCol,14);widths.set(legendCol+1,22);widths.set(legendCol+2,18);
 block(1,legendCol,1,legendCol+2,'BUSCAR MATERIAL · SIN MACROS',head);cell(2,legendCol,'Seleccionar código',label);cell(2,legendCol+1,'',selectorStyle);cell(3,legendCol,'Elige un código en la celda amarilla.',label);block(4,legendCol,4,legendCol+2,'LEYENDA DE MATERIALES',head);['Tipo','Código','Cantidad'].forEach((v,i)=>cell(5,legendCol+i,v,head));legendRows.forEach((item,i)=>{cell(i+6,legendCol,item.type);cell(i+6,legendCol+1,item.code,style(item.hex));cell(i+6,legendCol+2,item.qty);});lastRow=Math.max(lastRow,legendRows.length+5);
 // Dibujar bordes de cada ubicación y rack después de rellenar los pasillos.
 function outline(r,c,rr,cc,skipPaths=false){for(let y=r;y<=rr;y++)for(let x=c;x<=cc;x++){const mask=(x===c?1:0)|(x===cc?2:0)|(y===r?4:0)|(y===rr?8:0);if(!mask)continue;const current=data.get(y)?.get(x)||{v:'',s:white};if(skipPaths&&(current.s===path||current.s===verticalPath))continue;const source=styles[current.s];const existing=Number(source.match(/borderId="(\d+)"/)?.[1]||0);const combined=mask|(existing>=2&&existing<=16?existing-1:0);const key='outline:'+current.s+':'+combined;let id=cache.get(key);if(id===undefined){id=styles.length;styles.push(source.replace(/borderId="\d+"/,`borderId="${combined+1}"`));cache.set(key,id);}cell(y,x,current.v,id);}}
 for(const b of selectedBoxes){if(!b.rack||b.path||b.location==='JAULA')continue;const m=b.location.match(/^R(\d{2})([A-D])(\d{2})(?:\.(\d))?$/);if(!m)continue;const c=columns.get(Number(m[1])+':'+m[2]+(m[4]?'.'+m[4]:'')),r=bayRow(Number(m[3]));outline(r,c,r+baySlots.get(Number(m[3])),c);}
 for(const r of selectedRacks){const cols=[...columns].filter(([key])=>key.startsWith(r.r+':')).map(([,c])=>c);outline(r.r<=9?bayRow(14)-1:1,Math.min(...cols),lastStorage,Math.max(...cols),true);}
 if(scope==='all'){const zoneLast=columns.get('9:D');outline(3,1,bayRow(23)-1,zoneLast);outline(bayRow(23),1,shortStart-2,zoneLast);}
 const codes=[...new Set(legendRows.map(r=>r.code))].sort();const codeRows=codes.map((code,i)=>`<row r="${i+1}"><c r="A${i+1}" t="inlineStr"><is><t>${esc(code)}</t></is></c></row>`).join('');
 const rows=[...data].sort((a,b)=>a[0]-b[0]).map(([r,cells])=>`<row r="${r}" ht="${r===1?28:44}" customHeight="1">${[...cells].sort((a,b)=>a[0]-b[0]).map(([c,{v,s}])=>typeof v==='number'?`<c r="${col(c)}${r}" s="${s}"><v>${v}</v></c>`:`<c r="${col(c)}${r}" s="${s}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`).join('')}</row>`).join('');
 // Cada pareja código/cantidad tiene su propia regla: ambas celdas se resaltan.
 const cf=highlightRanges.map((range,i)=>{const top=range.split(':')[0],fixed=top.replace(/([A-Z]+)(\d+)/,'$$$1$$$2'),select='$'+col(legendCol+1)+'$2';return `<conditionalFormatting sqref="${range}"><cfRule type="expression" dxfId="0" priority="${i+1}"><formula>AND(${select}&lt;&gt;"",LEFT(${fixed},FIND(CHAR(10),${fixed}&amp;CHAR(10))-1)=${select})</formula></cfRule></conditionalFormatting>`;}).join('');
 const types='http://schemas.openxmlformats.org/package/2006/content-types',pkg='http://schemas.openxmlformats.org/package/2006/relationships';
 return zipStored({
 '[Content_Types].xml':`<Types xmlns="${types}"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${[1,2].map(n=>`<Override PartName="/xl/worksheets/sheet${n}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`,
 '_rels/.rels':`<Relationships xmlns="${pkg}"><Relationship Id="rId1" Type="${rel}/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
 'xl/workbook.xml':`<workbook xmlns="${ns}" xmlns:r="${rel}"><sheets><sheet name="Layout editable" sheetId="1" r:id="rId1"/><sheet name="Codigos" sheetId="2" state="hidden" r:id="rId2"/></sheets><definedNames><definedName name="ListaCodigos">Codigos!$A$1:$A$${Math.max(1,codes.length)}</definedName><definedName name="_xlnm.Print_Area" localSheetId="0">'Layout editable'!$A$1:$${col(legendCol+2)}$${lastRow}</definedName></definedNames><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>`,
 'xl/_rels/workbook.xml.rels':`<Relationships xmlns="${pkg}">${[1,2].map(n=>`<Relationship Id="rId${n}" Type="${rel}/worksheet" Target="worksheets/sheet${n}.xml"/>`).join('')}<Relationship Id="rId3" Type="${rel}/styles" Target="styles.xml"/></Relationships>`,
 'xl/styles.xml':`<styleSheet xmlns="${ns}"><fonts count="4"><font><sz val="14"/><name val="Calibri"/></font><font><b/><sz val="10"/><name val="Calibri"/></font><font><b/><sz val="12"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font><font><b/><sz val="64"/><color rgb="FF173B59"/><name val="Calibri"/></font></fonts><fills count="${fills.length}">${fills.join('')}</fills><borders count="19"><border><left/><right/><top/><bottom/><diagonal/></border><border>${['left','right','top','bottom'].map(s=>`<${s} style="thin"><color rgb="FF000000"/></${s}>`).join('')}<diagonal/></border>${Array.from({length:15},(_,i)=>`<border>${['left','right','top','bottom'].map((side,n)=>(i+1)&(1<<n)?`<${side} style="medium"><color rgb="FF000000"/></${side}>`:`<${side}/>`).join('')}<diagonal/></border>`).join('')}<border><left/><right/><top style="dashed"><color rgb="FFBF9518"/></top><bottom style="dashed"><color rgb="FFBF9518"/></bottom><diagonal/></border><border><left style="dashed"><color rgb="FFBF9518"/></left><right style="dashed"><color rgb="FFBF9518"/></right><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="${styles.length}">${styles.join('')}</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles><dxfs count="1"><dxf><font><b/><color rgb="FF000000"/></font><fill><patternFill patternType="solid"><fgColor rgb="FFFFFF00"/><bgColor rgb="FFFFFF00"/></patternFill></fill></dxf></dxfs></styleSheet>`,
 'xl/worksheets/sheet1.xml':`<worksheet xmlns="${ns}"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:${col(legendCol+2)}${lastRow}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0" zoomScale="40"/></sheetViews><sheetFormatPr defaultRowHeight="22"/><cols>${[...widths].sort((a,b)=>a[0]-b[0]).map(([c,w])=>`<col min="${c}" max="${c}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData>${rows}</sheetData><mergeCells count="${merges.length}">${merges.map(m=>`<mergeCell ref="${m}"/>`).join('')}</mergeCells>${cf}<dataValidations count="1"><dataValidation type="list" allowBlank="1" showErrorMessage="1" errorTitle="Código no válido" error="Elige un código de la lista." sqref="${selectRef}"><formula1>ListaCodigos</formula1></dataValidation></dataValidations><pageMargins left="0.25" right="0.25" top="0.25" bottom="0.25" header="0" footer="0"/><pageSetup paperSize="8" orientation="landscape" fitToWidth="1" fitToHeight="1"/></worksheet>`,
 'xl/worksheets/sheet2.xml':`<worksheet xmlns="${ns}"><sheetData>${codeRows}</sheetData></worksheet>`
 });
}
$('exportexcel').onclick=async()=>{
 const button=$('exportexcel');button.disabled=true;try{
 if(!records.length)throw Error('Carga tu plantilla antes de descargar el Excel.');
 const scope=$('exportscope').value,rack=$('rack').value,png=null;
 const rows=new Map();for(const r of records){if(scope==='rack'&&byLocation.get(r.location)?.rack!==Number(rack))continue;const key=JSON.stringify([r.type,r.code]);if(!rows.has(key))rows.set(key,{type:r.type,code:r.code,qty:0,hex:toHex(color(r.code))});rows.get(key).qty+=r.qty;}
 const legendRows=[...rows.values()].sort((a,b)=>a.type.localeCompare(b.type)||a.code.localeCompare(b.code,'es',{numeric:true}));
 const blob=buildLayoutWorkbook(png,1800,scope==='all'?1300:1800,legendRows),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download='Layout_'+(scope==='all'?'Completo':'Rack_'+rack)+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(href),30000);$('status').textContent='Excel editable descargado: elige el código en la celda amarilla junto a la leyenda. Sin macros.';
 }catch(e){$('status').textContent='Error: '+e.message;}finally{button.disabled=false;}
};
